version: 2
jobs:

  test:
    docker:
      - image: circleci/golang:1.12

    working_directory: ~/app
    steps:
      - checkout
      - run: go test -v -mod=vendor ./...
      - run: go build -mod=vendor .

  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: ~/app
    steps:
      - checkout
      - attach_workspace:
          at: ~/artifacts
      - run: 
          name: unit tests
          command: go test -v -mod=vendor ./...
      - persist_to_workspace:
          root: .
          paths: ./build

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
