version: 2
jobs:

  sonar:
    docker:
      - image: dmoscrop/circleci-sonar-scanner-docker
    steps:
      - checkout
      - run: sonar-scanner -Dsonar.projectKey=Soontao_PDISolutionCenter -Dsonar.organization=soontao-github -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=7f2974d6793e7395727658a1140fe7844e9a5cb4 -Dsonar.c.file.suffixes=- -Dsonar.cpp.file.suffixes=- -Dsonar.objc.file.suffixes=-

  test:
    docker:
      - image: circleci/golang:1.12

    working_directory: ~/app
    steps:
      - checkout
      - run: go test -v -mod=vendor ./...
      - run: go build -mod=vendor .

  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: ~/app
    steps:
      - checkout
      - attach_workspace:
          at: ~/artifacts
      - run: 
          name: unit tests
          command: go test -v -mod=vendor ./...
      - persist_to_workspace:
          root: .
          paths: ./build

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - sonar:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
